# Generated by Django 5.0 on 2024-01-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="business_fields",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="business_fields",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
