# Generated by Django 5.0 on 2024-01-14 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_remove_location_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Webpage",
        ),
    ]
