# Generated by Django 5.0 on 2024-01-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_delete_webpage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="experience_in_years_upper_end",
            new_name="maximal_experience_in_years",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="experience_in_years_lower_end",
            new_name="minimal_experience_in_years",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="non_tech_skills",
            new_name="non_tech_skill_requirements",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="salary_lower_end",
            new_name="salary_lower_bound",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="salary_upper_end",
            new_name="salary_upper_bound",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="tech_skills",
            new_name="tech_skill_requirements",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="employment_type",
            new_name="type_of_contract",
        ),
        migrations.RemoveField(
            model_name="job",
            name="job_id",
        ),
        migrations.AddField(
            model_name="job",
            name="short_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="tasks_and_responsibilities",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
