# Generated by Django 5.0 on 2024-01-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_company_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="vacant_since",
            field=models.DateField(auto_now_add=True),
        ),
    ]
